### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by NomarCub** [caronchen/obsidian-epub-plugin#2]
Epubs are unreadable in dark mode currently, black text on a dark background, also with a jarring white frame.  
(It happened with ones in my collection, and also [this public sample](https://github.com/IDPF/epub3-samples/releases/download/20170606/accessible_epub_3.epub) I found.)

![image](https://user-images.githubusercontent.com/5298006/169669730-622a3d91-cb87-466d-90ae-4280b6e5a801.png)

**Comment by caronchen** [comment]
Which theme are you using? That's my renderer result, default theme, dark mode.

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/150803/169932446-24fdb6d0-df10-4552-8fc0-9204d9ee75ab.png">
